services:
  db:
    image: postgres:15
    container_name: postgres_local_tt
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: tt_admin
      POSTGRES_PASSWORD: tt_admin
      POSTGRES_DB: tt_v0
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tt_admin -d tt_v0"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:

    build:
      context: .
      dockerfile: Dockerfile # образ собирается локально и загружается в контейнер

    # image: maksnd/tt_v0:1.1 # образ загружается из docker hub

    container_name: web_local_tt
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn TaskTracker.wsgi:application --bind 0.0.0.0:9000 --workers 4 --timeout 60 --max-requests 1000 --max-requests-jitter 100 --log-level info --access-logfile - --error-logfile -"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DEBUG: 'True'
      SECRET_KEY: 'your-secret-key-for-testing'
      # DJANGO_ALLOWED_HOSTS: '193.187.174.69'
      # DJANGO_ALLOWED_HOSTS: '127.0.0.1'
      DJANGO_ALLOWED_HOSTS: 'localhost'
      DB_NAME: tt_v0
      DB_USER: tt_admin
      DB_PASSWORD: tt_admin
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - .:/app # код монтируется в контейнер
      - ./staticfiles:/app/staticfiles:rw
      - ./media:/app/media:rw

  nginx:
    image: nginx:latest
    container_name: nginx_local_tt
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/app/staticfiles:ro
      - ./media:/app/media:ro
    depends_on:
      - web

volumes:
  postgres_data_local: 