# Generated by Django 5.2.2 on 2025-06-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_completed_at_alter_task_status_alter_task_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'permissions': [('can_create_task', 'Может создавать задачи'), ('can_edit_task', 'Может редактировать задачи')], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
